//! Agent pairing + approval — invite codes, onboarding pipeline, revocation.
//!
//! Flow: generate invite code → new agent redeems code → admin approves in hub
//! → agent gets device token → agent joins mesh with scoped peer visibility.

use std::collections::HashSet;
use std::net::SocketAddr;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use axum::extract::connect_info::ConnectInfo;
use axum::extract::{Path, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::IntoResponse;
use axum::Json;
use dashmap::DashMap;
use rand::Rng;
use serde::{Deserialize, Serialize};
use tracing::{info, warn};

use crate::AppState;

// ─── Structs ────────────────────────────────────────────────────────────────

/// Ephemeral invite code — in-memory only, 300s TTL.
struct InviteCode {
    created_by: String,
    created_at: Instant,
    used: bool,
}

/// An agent going through the onboarding pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingEntry {
    pub id: String,
    pub agent_name: String,
    pub peer_id: String,
    /// Empty until approval, then "dt_" + 32 hex.
    #[serde(skip_serializing_if = "String::is_empty")]
    pub device_token: String,
    /// "pending_approval" | "approved" | "rejected" | "revoked"
    pub status: String,
    pub created_at: f64,
    pub updated_at: f64,
}

/// POST /api/pairing/pair request body.
#[derive(Debug, Deserialize)]
pub struct PairRequest {
    pub code: String,
    pub agent_name: String,
}

// ─── State ──────────────────────────────────────────────────────────────────

pub struct PairingState {
    /// code string → InviteCode
    codes: DashMap<String, InviteCode>,
    /// id → OnboardingEntry
    onboarding: DashMap<String, OnboardingEntry>,
    /// IP → list of attempt timestamps (for rate limiting)
    rate_limits: DashMap<String, Vec<Instant>>,
}

const CODE_TTL_SECS: u64 = 300;
const RATE_LIMIT_WINDOW_SECS: u64 = 60;
const RATE_LIMIT_MAX_ATTEMPTS: usize = 5;

impl PairingState {
    pub fn new() -> Self {
        Self {
            codes: DashMap::new(),
            onboarding: DashMap::new(),
            rate_limits: DashMap::new(),
        }
    }

    /// Generate a 6-digit invite code.
    fn generate_code(&self, created_by: &str) -> String {
        let mut rng = rand::thread_rng();
        let code = format!("{:06}", rng.gen_range(0..1_000_000u32));
        self.codes.insert(
            code.clone(),
            InviteCode {
                created_by: created_by.to_string(),
                created_at: Instant::now(),
                used: false,
            },
        );
        info!("[PAIRING] invite code generated by {}", created_by);
        code
    }

    /// Consume a valid code. Returns the creator peer_id if valid.
    fn consume_code(&self, code: &str) -> Option<String> {
        let mut entry = self.codes.get_mut(code)?;
        let ic = entry.value_mut();
        if ic.used || ic.created_at.elapsed().as_secs() >= CODE_TTL_SECS {
            return None;
        }
        ic.used = true;
        Some(ic.created_by.clone())
    }

    /// Create a pending onboarding entry after valid code redemption.
    fn create_pending(&self, agent_name: &str) -> OnboardingEntry {
        let id = uuid::Uuid::new_v4().to_string()[..8].to_string();
        let peer_id = generate_peer_id();
        let now = epoch_now();
        let entry = OnboardingEntry {
            id: id.clone(),
            agent_name: agent_name.to_string(),
            peer_id,
            device_token: String::new(),
            status: "pending_approval".into(),
            created_at: now,
            updated_at: now,
        };
        self.onboarding.insert(id, entry.clone());
        entry
    }

    /// Approve a pending agent — generates device token.
    pub fn approve(&self, id: &str) -> Option<OnboardingEntry> {
        let mut entry = self.onboarding.get_mut(id)?;
        let e = entry.value_mut();
        if e.status != "pending_approval" {
            return None;
        }
        e.status = "approved".into();
        e.device_token = generate_device_token();
        e.updated_at = epoch_now();
        Some(e.clone())
    }

    /// Reject a pending agent.
    fn reject(&self, id: &str) -> Option<OnboardingEntry> {
        let mut entry = self.onboarding.get_mut(id)?;
        let e = entry.value_mut();
        if e.status != "pending_approval" {
            return None;
        }
        e.status = "rejected".into();
        e.updated_at = epoch_now();
        Some(e.clone())
    }

    /// Revoke an approved agent.
    pub fn revoke(&self, id: &str) -> Option<OnboardingEntry> {
        let mut entry = self.onboarding.get_mut(id)?;
        let e = entry.value_mut();
        if e.status != "approved" {
            return None;
        }
        e.status = "revoked".into();
        e.updated_at = epoch_now();
        Some(e.clone())
    }

    /// Validate a device token — returns entry if approved and not revoked.
    pub fn validate_device_token(&self, token: &str) -> Option<OnboardingEntry> {
        self.onboarding
            .iter()
            .find(|e| e.value().device_token == token && e.value().status == "approved")
            .map(|e| e.value().clone())
    }

    /// Set of peer_ids for all approved (not revoked) agents.
    pub fn approved_peer_ids(&self) -> HashSet<String> {
        self.onboarding
            .iter()
            .filter(|e| e.value().status == "approved")
            .map(|e| e.value().peer_id.clone())
            .collect()
    }

    /// Rate limit check: 5 attempts per 60s per IP.
    fn check_rate_limit(&self, ip: &str) -> bool {
        let now = Instant::now();
        let window = Duration::from_secs(RATE_LIMIT_WINDOW_SECS);
        let mut attempts = self
            .rate_limits
            .entry(ip.to_string())
            .or_insert_with(Vec::new);
        attempts.retain(|t| now.duration_since(*t) < window);
        if attempts.len() >= RATE_LIMIT_MAX_ATTEMPTS {
            return false;
        }
        attempts.push(now);
        true
    }

    /// Background cleanup: expired codes and stale rate-limit entries.
    pub async fn cleanup_loop(&self) {
        loop {
            tokio::time::sleep(Duration::from_secs(60)).await;

            // Remove expired / used codes
            let before = self.codes.len();
            self.codes
                .retain(|_, ic| !ic.used && ic.created_at.elapsed().as_secs() < CODE_TTL_SECS);
            let removed = before - self.codes.len();
            if removed > 0 {
                info!("[PAIRING] cleaned up {} expired invite codes", removed);
            }

            // Prune empty rate-limit buckets
            self.rate_limits.retain(|_, v| !v.is_empty());
        }
    }

    fn list_pending(&self) -> Vec<OnboardingEntry> {
        self.onboarding
            .iter()
            .filter(|e| e.value().status == "pending_approval")
            .map(|e| e.value().clone())
            .collect()
    }

    fn list_all(&self) -> Vec<OnboardingEntry> {
        self.onboarding.iter().map(|e| e.value().clone()).collect()
    }
}

// ─── Helpers ────────────────────────────────────────────────────────────────

/// Generate a device token: "dt_" + 32 hex chars (128-bit random).
fn generate_device_token() -> String {
    let mut rng = rand::thread_rng();
    let bytes: [u8; 16] = rng.gen();
    format!(
        "dt_{}",
        bytes.iter().map(|b| format!("{:02x}", b)).collect::<String>()
    )
}

/// Generate a peer ID: "agent-" + 6 hex chars.
fn generate_peer_id() -> String {
    let mut rng = rand::thread_rng();
    let bytes: [u8; 3] = rng.gen();
    format!(
        "agent-{}",
        bytes.iter().map(|b| format!("{:02x}", b)).collect::<String>()
    )
}

fn epoch_now() -> f64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs_f64()
}

// ─── HTTP Handlers ──────────────────────────────────────────────────────────

/// POST /api/pairing/generate-code — generate a 6-digit invite code.
/// Requires X-API-Key header (caller must be an existing mesh member).
pub async fn generate_code_handler(
    State(state): State<AppState>,
    headers: HeaderMap,
) -> Result<Json<serde_json::Value>, StatusCode> {
    // Verify caller is an authenticated mesh member
    let api_key = headers
        .get("x-api-key")
        .and_then(|v| v.to_str().ok())
        .ok_or(StatusCode::UNAUTHORIZED)?;

    let entry = state
        .auth
        .lookup_api_key(api_key)
        .ok_or(StatusCode::UNAUTHORIZED)?;

    let code = state.pairing.generate_code(&entry.peer_id);

    Ok(Json(serde_json::json!({
        "code": code,
        "expires_in": CODE_TTL_SECS,
    })))
}

/// POST /api/pairing/pair — redeem invite code, create pending onboarding entry.
/// Rate-limited by IP. No auth required (the code IS the auth).
pub async fn pair_handler(
    State(state): State<AppState>,
    ConnectInfo(addr): ConnectInfo<SocketAddr>,
    Json(body): Json<PairRequest>,
) -> impl IntoResponse {
    let ip = addr.ip().to_string();

    // Rate limit
    if !state.pairing.check_rate_limit(&ip) {
        warn!("[PAIRING] rate limit exceeded for {}", ip);
        return (
            StatusCode::TOO_MANY_REQUESTS,
            Json(serde_json::json!({ "error": "too many pairing attempts, try again later" })),
        )
            .into_response();
    }

    // Validate code format
    if body.code.len() != 6 || !body.code.chars().all(|c| c.is_ascii_digit()) {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "code must be exactly 6 digits" })),
        )
            .into_response();
    }

    let agent_name = body.agent_name.trim().to_string();
    if agent_name.is_empty() {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!({ "error": "agent_name is required" })),
        )
            .into_response();
    }

    // Consume the code
    let _invited_by = match state.pairing.consume_code(&body.code) {
        Some(creator) => creator,
        None => {
            warn!("[PAIRING] invalid or expired code from {}", ip);
            return (
                StatusCode::UNAUTHORIZED,
                Json(serde_json::json!({ "error": "invalid or expired pairing code" })),
            )
                .into_response();
        }
    };

    // Create pending entry
    let entry = state.pairing.create_pending(&agent_name);

    info!(
        "[PAIRING] pending approval: agent_name='{}' peer_id={} id={}",
        agent_name, entry.peer_id, entry.id
    );

    Json(serde_json::json!({
        "id": entry.id,
        "status": entry.status,
        "peer_id": entry.peer_id,
    }))
    .into_response()
}

/// GET /api/pairing/pending — list agents awaiting approval.
pub async fn list_pending_handler(State(state): State<AppState>) -> Json<Vec<OnboardingEntry>> {
    Json(state.pairing.list_pending())
}

/// GET /api/pairing/all — list all onboarding entries.
pub async fn list_all_handler(State(state): State<AppState>) -> Json<Vec<OnboardingEntry>> {
    Json(state.pairing.list_all())
}

/// POST /api/pairing/{id}/approve — approve a pending agent.
pub async fn approve_handler(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> impl IntoResponse {
    match state.pairing.approve(&id) {
        Some(entry) => {
            info!(
                "[PAIRING] approved: agent_name='{}' peer_id={} id={}",
                entry.agent_name, entry.peer_id, entry.id
            );
            Json(serde_json::json!({
                "id": entry.id,
                "status": entry.status,
                "peer_id": entry.peer_id,
                "device_token": entry.device_token,
            }))
            .into_response()
        }
        None => (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({ "error": "not found or not pending" })),
        )
            .into_response(),
    }
}

/// POST /api/pairing/{id}/reject — reject a pending agent.
pub async fn reject_handler(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> impl IntoResponse {
    match state.pairing.reject(&id) {
        Some(entry) => {
            info!("[PAIRING] rejected: id={}", entry.id);
            Json(serde_json::json!({ "status": "ok" })).into_response()
        }
        None => (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({ "error": "not found or not pending" })),
        )
            .into_response(),
    }
}

/// POST /api/pairing/{id}/revoke — revoke an approved agent.
pub async fn revoke_handler(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> impl IntoResponse {
    match state.pairing.revoke(&id) {
        Some(entry) => {
            info!("[PAIRING] revoked: peer_id={} id={}", entry.peer_id, entry.id);
            Json(serde_json::json!({ "status": "ok" })).into_response()
        }
        None => (
            StatusCode::NOT_FOUND,
            Json(serde_json::json!({ "error": "not found or not approved" })),
        )
            .into_response(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_code_format() {
        let state = PairingState::new();
        let code = state.generate_code("admin");
        assert_eq!(code.len(), 6);
        assert!(code.chars().all(|c| c.is_ascii_digit()));
    }

    #[test]
    fn test_consume_valid_code() {
        let state = PairingState::new();
        let code = state.generate_code("admin");
        let creator = state.consume_code(&code).unwrap();
        assert_eq!(creator, "admin");
    }

    #[test]
    fn test_consume_code_twice_fails() {
        let state = PairingState::new();
        let code = state.generate_code("admin");
        assert!(state.consume_code(&code).is_some());
        assert!(state.consume_code(&code).is_none());
    }

    #[test]
    fn test_consume_invalid_code() {
        let state = PairingState::new();
        assert!(state.consume_code("999999").is_none());
    }

    #[test]
    fn test_pairing_full_flow() {
        let state = PairingState::new();
        // Generate code
        let code = state.generate_code("admin");
        // Consume code
        let _creator = state.consume_code(&code).unwrap();
        // Create pending entry
        let entry = state.create_pending("my-agent");
        assert_eq!(entry.status, "pending_approval");
        assert!(entry.device_token.is_empty());
        // Approve
        let approved = state.approve(&entry.id).unwrap();
        assert_eq!(approved.status, "approved");
        assert!(!approved.device_token.is_empty());
        // Validate device token
        let validated = state.validate_device_token(&approved.device_token).unwrap();
        assert_eq!(validated.peer_id, approved.peer_id);
    }

    #[test]
    fn test_approve_generates_device_token() {
        let state = PairingState::new();
        let entry = state.create_pending("test-agent");
        let approved = state.approve(&entry.id).unwrap();
        assert!(approved.device_token.starts_with("dt_"));
        // "dt_" (3) + 32 hex = 35 total
        assert_eq!(approved.device_token.len(), 35);
    }

    #[test]
    fn test_reject_pending() {
        let state = PairingState::new();
        let entry = state.create_pending("test-agent");
        let rejected = state.reject(&entry.id).unwrap();
        assert_eq!(rejected.status, "rejected");
    }

    #[test]
    fn test_revoke_approved() {
        let state = PairingState::new();
        let entry = state.create_pending("test-agent");
        state.approve(&entry.id).unwrap();
        let revoked = state.revoke(&entry.id).unwrap();
        assert_eq!(revoked.status, "revoked");
    }

    #[test]
    fn test_cannot_approve_rejected() {
        let state = PairingState::new();
        let entry = state.create_pending("test-agent");
        state.reject(&entry.id).unwrap();
        assert!(state.approve(&entry.id).is_none());
    }

    #[test]
    fn test_cannot_revoke_pending() {
        let state = PairingState::new();
        let entry = state.create_pending("test-agent");
        assert!(state.revoke(&entry.id).is_none());
    }

    #[test]
    fn test_validate_device_token_revoked() {
        let state = PairingState::new();
        let entry = state.create_pending("test-agent");
        let approved = state.approve(&entry.id).unwrap();
        let token = approved.device_token.clone();
        state.revoke(&entry.id).unwrap();
        assert!(state.validate_device_token(&token).is_none());
    }

    #[test]
    fn test_approved_peer_ids() {
        let state = PairingState::new();
        let e1 = state.create_pending("agent-a");
        let e2 = state.create_pending("agent-b");
        let _e3 = state.create_pending("agent-c"); // stays pending
        state.approve(&e1.id).unwrap();
        state.approve(&e2.id).unwrap();
        let ids = state.approved_peer_ids();
        assert_eq!(ids.len(), 2);
        assert!(ids.contains(&e1.peer_id));
        assert!(ids.contains(&e2.peer_id));
    }

    #[test]
    fn test_rate_limit_allows_5() {
        let state = PairingState::new();
        for _ in 0..5 {
            assert!(state.check_rate_limit("10.0.0.1"));
        }
    }

    #[test]
    fn test_rate_limit_blocks_6th() {
        let state = PairingState::new();
        for _ in 0..5 {
            state.check_rate_limit("10.0.0.2");
        }
        assert!(!state.check_rate_limit("10.0.0.2"));
    }

    #[test]
    fn test_device_token_format() {
        let token = generate_device_token();
        assert!(token.starts_with("dt_"));
        assert_eq!(token.len(), 35); // "dt_" + 32 hex
        assert!(token[3..].chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn test_peer_id_format() {
        let pid = generate_peer_id();
        assert!(pid.starts_with("agent-"));
        assert_eq!(pid.len(), 12); // "agent-" + 6 hex
        assert!(pid[6..].chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn test_list_pending_filters() {
        let state = PairingState::new();
        let e1 = state.create_pending("a");
        let e2 = state.create_pending("b");
        state.approve(&e1.id).unwrap();
        let pending = state.list_pending();
        assert_eq!(pending.len(), 1);
        assert_eq!(pending[0].id, e2.id);
    }
}
